---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: new-sql-pvc-31445
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: dellcsi-powerstore-sc