---
kind: Service
apiVersion: v1
metadata:
  name: mssql-service-31445
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31445
  selector:
    app: mssql-31445