---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rootca-cert
  namespace: demo
data:
  rootCA.crt: |
    -----BEGIN CERTIFICATE-----
    MIID9zCCAt+gAwIBAgIUKeay3nw4sQe8QHbIlPr8q4vK7AMwDQYJKoZIhvcNAQEL
    BQAwgYoxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTESMBAGA1UEBwwJSG9wa2lu
    dG9uMQ0wCwYDVQQKDAREZWxsMQ8wDQYDVQQLDAZCaXpBcHAxGDAWBgNVBAMMD0hB
    UHJveHkgUm9vdCBDQTEgMB4GCSqGSIb3DQEJARYRYWRtaW5AcmljaHAubG9jYWww
    HhcNMjIwOTE5MjAyNjQ0WhcNMjYwOTE4MjAyNjQ0WjCBijELMAkGA1UEBhMCVVMx
    CzAJBgNVBAgMAk1BMRIwEAYDVQQHDAlIb3BraW50b24xDTALBgNVBAoMBERlbGwx
    DzANBgNVBAsMBkJpekFwcDEYMBYGA1UEAwwPSEFQcm94eSBSb290IENBMSAwHgYJ
    KoZIhvcNAQkBFhFhZG1pbkByaWNocC5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAKSSPjwrZROMjzAj/XWHrN5oZj8svUmWMhRQxOQZRL3z25Z+
    iD4xfxPBd7I/jmHozo9snIuiWXTUWDVIabO5LORy9JRbybmyzy3+KyEcrsz9w9Oi
    AYN7Ur6HOP0Cd5hTx4m4WW/xjMhjlw7TQIlFhXx8oLV+7I8HOKI70AWZttKsmTSF
    2grUI+VDDjcny29X4C7hKsz08+FSeXqUZbvZw4zRIHiNiNoPCnC1P/UszzaBtZzN
    AT8gGa5mTZj2HNuFCxQX2d9kcUR024EAJsg7r4Wy5kt7pHZIsRRx2Zh5fWmtCssf
    iS9B0mgz73w85tw0sCPd+jVqIa6nWm7MZ5aU2X0CAwEAAaNTMFEwHQYDVR0OBBYE
    FBjBvyP7XDvhE4OATjTcksQL2AdgMB8GA1UdIwQYMBaAFBjBvyP7XDvhE4OATjTc
    ksQL2AdgMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAF7GX+Na
    PDpPbAO2yRiuwFGWh9ESqMV4vRoYklAqwWmToDsS/QMo8L4jn+0Uw+0SVm/1RWaw
    eArZA/yOTBA695BN1DRFhHoebqUZxev8QICkRBvdQ2yzPXOz/YHT7EiFzHVzeeLD
    jY1A1QO3KZPRFucXmdN1GSzDaqkGNALHRYLsvvMO8dFxs07QrF/DwRStcIAqrdc1
    4/XHKa9DXk8g9pBvSpF7HC1DJRee7ZnJ6p4Vme9LyXjmA+OBzaovOU4i54iKwvkl
    qXXlevx+E0KLy1QbhL9n49F2zi0SZRsjJ5+A5+gCz9CKhLL9b7VvsYqg/Ok40ZT8
    to7ahH31PTtnrzM=
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: demo
data:
  MSSQL_SA_PASSWORD: QFZhbnRhZ2U0
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: new-sql-pvc-31445
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: dellcsi-powerstore-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-sql-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql-31445
  template:
    metadata:
      labels:
        app: mssql-31445
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: docker.io/sanran/sql22-polybase-with-cert:v2-t13702
        resources:
          requests:
            memory: "128G"
            cpu: "12000m"
          limits:
            memory: "128G"
            cpu: "12000m"
        ports:
        - containerPort: 31445
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        - name: rootca-cert
          mountPath: /var/opt/mssql/security/ca-certificates/rootCA.crt
          subPath: rootCA.crt
          readOnly: true
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: new-sql-pvc-31445
      - name: rootca-cert
        configMap:
          name: rootca-cert
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-service-31445
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31445
  selector:
    app: mssql-31445